server:
  port: 10086
spring:
  application:
    name: ly-registry
eureka:
  client:
    register-with-eureka: false # 向别的eureka注册
    fetch-registry: false # 拉取服务
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

