server:
  port: 8087
spring:
  application:
    name: auth-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
ly:
  jwt:
    secret: ly@Login(Auth}*^31)&dongFeng% # 登录校验的密钥
    pubKeyPath: D:/develop/IdeaProjects/main-frame/leyou/rsa/rsa.pub # 公钥地址
    priKeyPath: D:/develop/IdeaProjects/main-frame/leyou/rsa/rsa.pri # 私钥地址
#    priKeyPath: D:\develop\IdeaProjects\main-frame\leyou\rsa\rsa.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
    cookie_name: LY_TOKEN
